In [ ]:
import numpy as np
import pandas as pd

In [ ]:
list = [10,20,30,40,50]
array = np.array(list)
array

array([10, 20, 30, 40, 50])

In [ ]:
tuple = (1,2,3,4,5)
array = np.array(tuple)
array

array([1, 2, 3, 4, 5])

In [ ]:
{'a':1, 'b':2, 'c':3}

In [ ]:
dictionary = {'a' : 1 , 'b' : 2 , 'c' : 3}
array = np.array(dictionary)
array

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [ ]:
series = pd.Series([10, 20, 30, 40, 50])

arr1 = series.values
arr2 = series.to_numpy()

print(arr1)
print(arr2)

[10 20 30 40 50]
[10 20 30 40 50]


In [ ]:
lst = [[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]

arr = np.array(lst)

print(arr)
print("Shape:", arr.shape)

In [ ]:
arr = np.zeros(10)

print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
arr = np.ones((3, 4))

print(arr)

In [ ]:
arr = np.arange(0, 21, 2)

print(arr)

In [ ]:
arr = np.linspace(1, 5, 10)

print(arr)

In [ ]:
arr = np.eye(3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr = np.random.randint(1, 101, size=(4, 4))

print(arr)

[[15 40  1 47]
 [67  3 17 26]
 [39 26 29 11]
 [85  9 59 27]]


In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimensions:", arr.ndim)

In [ ]:
arr = np.array([10, 20, 30, 40])

print("Data type:", arr.dtype)

In [ ]:
arr = np.array([10, 20, 30, 40])

print("Bytes per element:", arr.itemsize)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

float_arr = arr.astype(float)

print(float_arr)
print(float_arr.dtype)

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[2])

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])

print(arr[:3])

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

column = arr[:, 1]

print(column)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr[::-1])

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(arr[2:7])

In [ ]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

sub = arr[1:3, 1:3]

print(sub)

In [ ]:
arr = np.arange(1, 13)

matrix = arr.reshape(3, 4)

print(matrix)

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flat1 = arr.flatten()
flat2 = arr.ravel()

print(flat1)
print(flat2)

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.T)

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

vertical = np.vstack((a, b))
horizontal = np.hstack((a, b))

print("Vertical:")
print(vertical)

print("Horizontal:")
print(horizontal)

In [ ]:
arr = np.arange(12)

parts = np.array_split(arr, 3)

for part in parts:
    print(part)

In [ ]:
arr = np.array([10, 20, 30, 40])

# Insert 25 at index 2
new_arr = np.insert(arr, 2, 25)

print("After insertion:", new_arr)

# Delete element at index 2
deleted_arr = np.delete(arr, 2)

print("After deletion:", deleted_arr)

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard deviation:", np.std(arr))

In [ ]:
arr = np.array([[1, 8, 3],
                [7, 2, 9],
                [4, 6, 5]])

print("Row maximum:", np.max(arr, axis=1))
print("Row minimum:", np.min(arr, axis=1))

print("Column maximum:", np.max(arr, axis=0))
print("Column minimum:", np.min(arr, axis=0))

In [ ]:
a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

In [ ]:
arr = np.array([1, 2, 3, 4])

print("Cumulative sum:", np.cumsum(arr))
print("Cumulative product:", np.cumprod(arr))

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print("Variance:", np.var(arr))

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

even = arr[arr % 2 == 0]

print(even)

In [ ]:
arr = np.array([-5, 10, -3, 20, -1, 30])

result = np.where(arr < 0, 0, arr)

print(result)

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

mean = np.mean(arr)

result = arr[arr > mean]

print("Mean:", mean)
print("Elements greater than mean:", result)

In [ ]:
arr = np.array([1, 6, 8, 3, 10, 2, 7])

count = np.count_nonzero(arr > 5)

print(count)

In [ ]:
arr = np.array([50, 20, 40, 10, 30])

arr.sort()

print(arr)

In [ ]:
arr = np.array([50, 20, 40, 10, 30])

descending = np.sort(arr)[::-1]

print(descending)

In [ ]:
arr = np.array([50, 20, 40, 10, 30])

indices = np.argsort(arr)

print(indices)

In [ ]:
arr = np.array([[3, 1, 2],
                [9, 7, 8],
                [6, 5, 4]])

row_sorted = np.sort(arr, axis=1)
column_sorted = np.sort(arr, axis=0)

print("Row-wise:")
print(row_sorted)

print("Column-wise:")
print(column_sorted)

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

result = arr + 10

print(result)

In [ ]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

arr1d = np.array([10, 20, 30])

result = arr2d * arr1d

print(result)

In [ ]:
a = np.array([10, 20, 30, 40])
b = np.array([15, 20, 25, 40])

result = a == b

print(result)

In [ ]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

result = np.dot(A, B)

print(result)

In [ ]:
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

det = np.linalg.det(A)

print("Determinant:", det)

In [ ]:
A = np.array([[1, 2],
              [3, 4]])

inverse = np.linalg.inv(A)

print(inverse)

In [ ]:
A = np.array([[4, 1],
              [2, 3]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("Eigenvectors:")
print(eigenvectors)

In [ ]:
arr = np.random.rand(5)

print(arr)

In [ ]:
arr = np.random.randint(10, 51, size=(3, 3))

print(arr)

In [ ]:
np.random.seed(42)

arr1 = np.random.rand(5)

print(arr1)

In [ ]:
np.random.seed(42)
print(np.random.rand(5))

In [ ]:
arr = np.random.normal(size=10)

print(arr)

In [ ]:
arr = np.random.normal(loc=0, scale=1, size=10)

print(arr)